services:
  db:
    container_name: postgres
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: db_password
    networks:
      - app-network
    restart: always

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user_name:db_password@db/db
      SECRET_KEY: django-insecure-c5br57^imn$9=pen&bwevh7u)ip5^!#+$spk6h-%jh=skhpx9r
      DEBUG: False
      EMAIL_HOST_USER: batbook2025@gmail.com
      EMAIL_HOST_PASSWORD: ...
      deploy: True
      ACCESS_TOKEN_LIFETIME: 07-00-00
      REFRESH_TOKEN_LIFETIME: 30-00-00
      RESEND_API_KEY: ....
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network
    restart: always

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network: